Rp3.Test.Web/Controllers/BalanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rp3.Test.Web.Controllers
{
    public class BalanceController : Controller
    {
        // GET: Balance
        public ActionResult Index()
        {
            return View();
        }
    }
}

Rp3.Test.Web/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rp3.Test.Web.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {
            return View();
        }
    }
}

Rp3.Test.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rp3.Test.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Rp3.Test.Web/Controllers/RegistrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rp3.Test.Web.Controllers
{
    public class RegistrarController : Controller
    {
        // GET: Registrar
        public ActionResult Index()
        {
            return View();
        }
    }
}

Rp3.Test.Web/Views/Balance/Index.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>

    <div class="jumbotron">
        <h1>Mis Transacciones</h1>

        <h2>Registro de Ingresos y Gastos</h2>

        <div id="">
            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Fecha Inicio</label>
                    <input type="date" class="form-control" id="txtFechaI">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Fecha Final</label>
                    <input type="date" class="form-control" id="txtFechaF">
                </div>
            </form>
        </div>
        <button class="btn btn-default" id="btnBuscar">Buscar</button>
        <button class="btn btn-default" id="btnNuevo">Nuevo</button>
    </div>

        <div>
            <table id="tblTransaccion" class="table table-striped"></table>
        </div>

        <div id="popup" class="hide" >
            <form>
                <div class="form-group">
                    <label>Categoria</label>
                    <select id="ctSelect" name="ctSelect"></select>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Tipo Transaccion</label>
                    <select id="trtSelect" name="trtSelect"></select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Descripcion</label>
                    <input type="text" class="form-control" id="txtDescripcion" placeholder="Ingrese Descripcion">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Fecha Registro</label>
                    <input type="date" class="form-control" id="txtFecha" placeholder="Ingrese Notas">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Valor</label>
                    <input type="number" class="form-control" id="txtvalor" placeholder="Ingrese Monto">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Notas</label>
                    <input type="text" class="form-control" id="txtNotas" placeholder="Ingrese Notas">
                </div>

                <button type="button" class="btn btn-primary" id="saveTR">Guardar</button>
            </form>

        </div>

</body>
<script language="JavaScript" type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/js/Balance.js"></script>
<script src="~/js/jquery.dataTables.min.js"></script>
</html>

Rp3.Test.Web/Views/Categoria/Index.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        <h2>Categoria</h2>
        <p>Agregue o revise los Rubros Disponibles.</p>
    </div>
</body>
<script language="JavaScript" type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
</html>

Rp3.Test.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Rp3.Test.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Rp3.Test.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Balance</h1>
    <p class="lead">Bitacora de mis Ingresos y Gastos.</p>
    <p>Seleccione un Usuario</p>
    <select id="clSelect" name="clSelect">
       
    </select>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Resumen</h2>
        <p>
            Ver el resumen de mi Balance
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index","Balance")">Ir a Balance</a></p>
    </div>
    <div class="col-md-4">
        <h2>Registrar</h2>
        <p>Revise su Balance o Ingrese nuevas Transacciones</p>
        <p><a class="btn btn-default" href="@Url.Action("Index","Registrar")">Ir a Registrar</a></p>
    </div>
    <div class="col-md-4">
        <h2>Categoria</h2>
        <p>Agregue o revise los Rubros Disponibles.</p>
        <p><a class="btn btn-default" href="@Url.Action("Index","Categoria")">Ir a Categoria</a></p>
    </div>
</div>

<script language="JavaScript" type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/js/Index.js"></script>

Rp3.Test.Web/Views/Registrar/Index.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>

    <div class="jumbotron">
        <h1>Balance</h1>

        <h2>Resumen por Categorias</h2>

        
    </div>

    <div>
        <table>
            <tr>
                <th>Categoria</th>
                <th>Saldo</th>
            </tr>
            <tr>
                <td>Remuneracion</td>
                <td>Valor</td>
            </tr>
            <tr>
                <td>Bonos</td>
                <td>Valor</td>
            </tr>
            <tr>
                <td>Alimentacion</td>
                <td>Valor</td>
            </tr>
            <tr>
                <td>Transporte</td>
                <td>Valor</td>
            </tr>
            <tr>
                <td>Total</td>
                <td>Valor</td>
            </tr>
        </table>
    </div>
</body>
</html>

Rp3.Test.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC TEST", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>